/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
import java.util.Random;
import javax.swing.JOptionPane;
public class Game extends javax.swing.JFrame {
    static int loop=0;
    static int counter=0;
    static int[] arr={0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
    static int max=75;
    static int min=1;
    static int countmenu=0;
    static int bb;
    static int uuu=1;
    static int maxb=75;
    static int minb=1;
    static int loopb=0;
    static int countb=0;
    static int[] arrb=new int[75];
    /**
     * Creates new form Game
     */
    public Game() {
        for(int i=0;i<75;i++){
            arrb[i]=0;
        }
        initComponents();
    }
     boolean checkb(int z){
        loopb++;
        if(loopb==1){
            arrb[0]=z;
        }
        else{
            for(int i=0;i<25;i++){
                if(z==arrb[i]){
                    return false;
                }
            }
            countb++;
            arrb[countb]=z;
        }
        return true;
    }
    boolean check(int z){
        loop++;
        if(loop==1){
            arr[0]=z;
        }
        else{
            for(int i=0;i<25;i++){
                if(z==arr[i]){
                    return false;
                }
            }
            counter++;
            arr[counter]=z;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(136, 242, 249));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(null);

        jButton1.setText("4");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(120, 40, 50, 23);

        jButton2.setText("26");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(180, 40, 50, 23);

        jButton3.setText("43");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(240, 40, 45, 23);

        jButton4.setText("59");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(300, 40, 50, 23);

        jButton5.setText("70");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(360, 40, 50, 23);

        jButton6.setText("9");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(120, 70, 50, 23);

        jButton7.setText("30");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(180, 70, 50, 23);

        jButton8.setText("41");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(240, 70, 45, 23);

        jButton9.setText("55");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(300, 70, 50, 23);

        jButton10.setText("68");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(360, 70, 50, 23);

        jButton11.setText("7");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(120, 100, 50, 23);

        jButton12.setText("23");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(180, 100, 50, 23);

        jButton13.setText("50");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(300, 100, 50, 23);

        jButton14.setText("63");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(360, 100, 50, 23);

        jButton15.setText("8");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);
        jButton15.setBounds(120, 130, 50, 23);

        jButton16.setText("20");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16);
        jButton16.setBounds(180, 130, 50, 23);

        jButton17.setText("31");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17);
        jButton17.setBounds(240, 130, 50, 23);

        jButton18.setText("60");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18);
        jButton18.setBounds(300, 130, 50, 23);

        jButton19.setText("75");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19);
        jButton19.setBounds(360, 130, 50, 23);

        jButton20.setText("13");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton20);
        jButton20.setBounds(120, 160, 50, 23);

        jButton21.setText("18");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton21);
        jButton21.setBounds(180, 160, 50, 23);

        jButton22.setText("34");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton22);
        jButton22.setBounds(240, 160, 50, 23);

        jButton23.setText("52");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton23);
        jButton23.setBounds(300, 160, 50, 23);

        jButton24.setText("69");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton24);
        jButton24.setBounds(365, 160, 45, 23);

        jLabel2.setBackground(new java.awt.Color(0, 51, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Free");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 100, 50, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BINGO!");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 14, 230, 20);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 0, 340, 230);

        jPanel2.setBackground(new java.awt.Color(153, 255, 51));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Called Number:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Update Call Board");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Call Bingo!");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Restart");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Refresh My Card");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if(countmenu>25)
            JOptionPane.showMessageDialog(rootPane, "You can call a max of 25 times");
        int z;
            z=min+(int)(Math.random()*(max-min+1));
            if (check(z)){
                jTextField1.setText(Integer.toString(z));
                try{
                    Thread.sleep(2000);
                }catch(InterruptedException e){}
             }
        countmenu++;
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(jButton1.getText())){
            jButton1.setText("X");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "False click \n You Lose");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(jButton2.getText())){
            jButton2.setText("X");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "False click \n You Lose");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(jButton3.getText())){
            jButton3.setText("X");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "False click \n You Lose");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(jButton4.getText())){
            jButton4.setText("X");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "False click \n You Lose");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(jButton5.getText())){
            jButton5.setText("X");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "False click \n You Lose");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(jButton6.getText())){
            jButton6.setText("X");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "False click \n You Lose");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(jButton7.getText())){
            jButton7.setText("X");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "False click \n You Lose");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(jButton8.getText())){
            jButton8.setText("X");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "False click \n You Lose");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(jButton9.getText())){
            jButton9.setText("X");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "False click \n You Lose");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(jButton10.getText())){
            jButton10.setText("X");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "False click \n You Lose");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(jButton11.getText())){
            jButton11.setText("X");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "False click \n You Lose");
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(jButton12.getText())){
            jButton12.setText("X");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "False click \n You Lose");
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(jButton13.getText())){
            jButton13.setText("X");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "False click \n You Lose");
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(jButton14.getText())){
            jButton14.setText("X");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "False click \n You Lose");
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(jButton15.getText())){
            jButton15.setText("X");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "False click \n You Lose");
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(jButton16.getText())){
            jButton16.setText("X");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "False click \n You Lose");
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(jButton17.getText())){
            jButton17.setText("X");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "False click \n You Lose");
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(jButton18.getText())){
            jButton18.setText("X");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "False click \n You Lose");
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(jButton19.getText())){
            jButton19.setText("X");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "False click \n You Lose");
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(jButton20.getText())){
            jButton20.setText("X");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "False click \n You Lose");
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(jButton21.getText())){
            jButton21.setText("X");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "False click \n You Lose");
        }
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(jButton22.getText())){
            jButton22.setText("X");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "False click \n You Lose");
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(jButton23.getText())){
            jButton23.setText("X");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "False click \n You Lose");
        }
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(jButton24.getText())){
            jButton24.setText("X");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "False click \n You Lose");
        }
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
         while(uuu<=24){
            bb=minb+(int)(Math.random()*(maxb-minb+1));
            if(checkb(bb)){
            switch(uuu){
            case 1: jButton1.setText(Integer.toString(bb));
                    break;
            case 2: jButton2.setText(Integer.toString(bb));
                    break;
            case 3: jButton3.setText(Integer.toString(bb));
                    break;
            case 4: jButton4.setText(Integer.toString(bb));
                    break;
            case 5: jButton5.setText(Integer.toString(bb));
                    break;
            case 6: jButton6.setText(Integer.toString(bb));
                    break;
            case 7: jButton7.setText(Integer.toString(bb));
                    break;
            case 8: jButton8.setText(Integer.toString(bb));
                    break;
            case 9: jButton9.setText(Integer.toString(bb));
                    break;
            case 10: jButton10.setText(Integer.toString(bb));
                    break;
            case 11: jButton11.setText(Integer.toString(bb));
                    break;
            case 12: jButton12.setText(Integer.toString(bb));
                    break;
            case 13: jButton13.setText(Integer.toString(bb));
                    break;
            case 14: jButton14.setText(Integer.toString(bb));
                    break;
            case 15: jButton15.setText(Integer.toString(bb));
                    break;
            case 16: jButton16.setText(Integer.toString(bb));
                    break;
            case 17: jButton17.setText(Integer.toString(bb));
                    break;
            case 18: jButton18.setText(Integer.toString(bb));
                    break;
            case 19: jButton19.setText(Integer.toString(bb));
                    break;
            case 20: jButton20.setText(Integer.toString(bb));
                    break;
            case 21: jButton21.setText(Integer.toString(bb));
                    break;
            case 22: jButton22.setText(Integer.toString(bb));
                    break;
            case 23: jButton23.setText(Integer.toString(bb));
                    break;
            case 24: jButton24.setText(Integer.toString(bb));
                    break;
            default: JOptionPane.showMessageDialog(rootPane,"Over");
            }
        uuu++;
            }
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        if(jButton1.getText().equals(jButton6.getText().equals(jButton11.getText().equals(jButton15.getText().equals(jButton20.getText())))))
            JOptionPane.showMessageDialog(rootPane, "You Won");
        else if(jButton2.getText().equals(jButton7.getText().equals(jButton12.getText().equals(jButton16.getText().equals(jButton21.getText())))))
            JOptionPane.showMessageDialog(rootPane, "You Won");
        else if(jButton4.getText().equals(jButton9.getText().equals(jButton13.getText().equals(jButton18.getText().equals(jButton23.getText())))))
            JOptionPane.showMessageDialog(rootPane, "You Won");
        else if(jButton5.getText().equals(jButton10.getText().equals(jButton14.getText().equals(jButton19.getText().equals(jButton24.getText())))))
            JOptionPane.showMessageDialog(rootPane, "You Won");
        else if(jButton1.getText().equals(jButton2.getText().equals(jButton3.getText().equals(jButton4.getText().equals(jButton5.getText())))))
            JOptionPane.showMessageDialog(rootPane, "You Won");
        else if(jButton6.getText().equals(jButton7.getText().equals(jButton8.getText().equals(jButton9.getText().equals(jButton10.getText())))))
            JOptionPane.showMessageDialog(rootPane, "You Won");
        else if(jButton11.getText().equals(jButton12.getText().equals(jButton13.getText().equals(jButton14.getText()))))
            JOptionPane.showMessageDialog(rootPane, "You Won");
        else if(jButton15.getText().equals(jButton16.getText().equals(jButton17.getText().equals(jButton18.getText().equals(jButton19.getText())))))
            JOptionPane.showMessageDialog(rootPane, "You Won");
        else if(jButton20.getText().equals(jButton21.getText().equals(jButton22.getText().equals(jButton23.getText().equals(jButton24.getText())))))
            JOptionPane.showMessageDialog(rootPane, "You Won");
        else if(jButton3.getText().equals(jButton8.getText().equals(jButton17.getText().equals(jButton22.getText()))))
            JOptionPane.showMessageDialog(rootPane, "You Won");
        else
            JOptionPane.showMessageDialog(rootPane, "False Bingo! call.\n You Lose for cheating!");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
